/// <reference types="cypress" />

context('Evolution contact form tests', () => {
  beforeEach(() => {
    cy.visit('https://evolutionit.bg')
  })

  describe('Body - contact form', () => {
    it('Check the contact form map', () => {
      cy.get('iframe').should('be.visible').should('have.attr', 'aria-label', 'улица „Академик Методи Попов“ 24а, София')
    })

    it('Check the contact form with valid input', () => {
      cy.get('#mainNav a[href="#contact"]').click()
      cy.get('[name="your-name"]').type('Tester')
      cy.get('[name="your-email"]').type('tester@tester.bg')
      cy.get('[name="your-phone"]').type('1-call-tester')
      cy.get('[name="your-subject"]').type('How are you doing?')
      cy.get('[name="your-message"]').type('Evolution!')
      cy.get('[type="submit"]').click()
      cy.get('[class="wpcf7-response-output"]')
        .should('contain', 'Thank you for your message. It has been sent.')
    })

    it('Check the contact form with invalid name input', () => {
      cy.get('#mainNav a[href="#contact"]').click()
      cy.get('[name="your-name"]').should('be.empty')
      cy.get('[name="your-email"]').type('tester@tester.bg')
      cy.get('[name="your-phone"]').type('1-call-tester')
      cy.get('[name="your-subject"]').type('How are you doing?')
      cy.get('[name="your-message"]').type('Evolution!')
      cy.get('[type="submit"]').click()
      cy.get('.wpcf7-not-valid-tip').should('have.text', 'The field is required.')
        .should('have.css', 'color', 'rgb(220, 50, 50)')
      cy.get('[class="wpcf7-response-output"]')
        .should('contain', 'One or more fields have an error. Please check and try again.')
        .should('have.css', 'box-sizing', 'border-box')
        .should('have.css', 'border-bottom-color', 'rgb(255, 185, 0)')
        .should('have.css', 'border-left-color', 'rgb(255, 185, 0)')
        .should('have.css', 'border-right-color', 'rgb(255, 185, 0)')
        .should('have.css', 'border-top-color', 'rgb(255, 185, 0)')
    })

    it('Check the contact form with invalid email input', () => {
      cy.get('#mainNav a[href="#contact"]').click()
      cy.get('[name="your-name"]').type('Tester')
      cy.get('[name="your-email"]').should('be.empty')
      cy.get('[name="your-phone"]').type('1-call-tester')
      cy.get('[name="your-subject"]').type('How are you doing?')
      cy.get('[name="your-message"]').type('Evolution!')
      cy.get('[type="submit"]').click()
      cy.get('.wpcf7-not-valid-tip').should('have.text', 'The field is required.')
        .should('have.css', 'color', 'rgb(220, 50, 50)')
      cy.get('[class="wpcf7-response-output"]')
        .should('contain', 'One or more fields have an error. Please check and try again.')
        .should('have.css', 'box-sizing', 'border-box')
        .should('have.css', 'border-bottom-color', 'rgb(255, 185, 0)')
        .should('have.css', 'border-left-color', 'rgb(255, 185, 0)')
        .should('have.css', 'border-right-color', 'rgb(255, 185, 0)')
        .should('have.css', 'border-top-color', 'rgb(255, 185, 0)')
    })

    it('Check the contact form with invalid subject input', () => {
      cy.get('#mainNav a[href="#contact"]').click()
      cy.get('[name="your-name"]').type('Tester')
      cy.get('[name="your-email"]').type('tester@tester.bg')
      cy.get('[name="your-phone"]').type('1-call-tester')
      cy.get('[name="your-subject"]').should('be.empty')
      cy.get('[name="your-message"]').type('Evolution!')
      cy.get('[type="submit"]').click()
      cy.get('.wpcf7-not-valid-tip').should('have.text', 'The field is required.')
        .should('have.css', 'color', 'rgb(220, 50, 50)')
      cy.get('[class="wpcf7-response-output"]')
        .should('contain', 'One or more fields have an error. Please check and try again.')
    })

    it('Check the contact form with invalid message body input', () => {
      cy.get('#mainNav a[href="#contact"]').click()
      cy.get('[name="your-name"]').type('Tseter')
      cy.get('[name="your-email"]').type('tester@tester.bg')
      cy.get('[name="your-phone"]').type('1-call-tester')
      cy.get('[name="your-subject"]').type('How are you doing?')
      cy.get('[name="your-message"]').should('be.empty')
      cy.get('[type="submit"]').click()
      cy.get('.wpcf7-not-valid-tip').should('have.text', 'The field is required.')
        .should('have.css', 'color', 'rgb(220, 50, 50)')
      cy.get('[class="wpcf7-response-output"]')
        .should('contain', 'One or more fields have an error. Please check and try again.')
        .should('have.css', 'box-sizing', 'border-box')
        .should('have.css', 'border-bottom-color', 'rgb(255, 185, 0)')
        .should('have.css', 'border-left-color', 'rgb(255, 185, 0)')
        .should('have.css', 'border-right-color', 'rgb(255, 185, 0)')
        .should('have.css', 'border-top-color', 'rgb(255, 185, 0)')
    })
  })
})